language: php

php:
  - 7.1.25

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - "./vendor/bin/phpunit" TestAnswer tests/Unit/TestAnswer.php
  - "./vendor/bin/phpunit" TestQuestion tests/Unit/TestQuestion.php
  - "./vendor/bin/phpunit" TestQuiz tests/Unit/TestQuiz.php
  - "./vendor/bin/phpunit" TestUserAnswer tests/Unit/TestUserAnswer.php
  - "./vendor/bin/phpunit" TestUserQuiz tests/Unit/TestUserQuiz.php